# Generated by Django 5.2.13 on 2026-04-14 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('apy', models.DecimalField(decimal_places=2, help_text='APY percentage e.g. 14.20', max_digits=6)),
                ('duration_days', models.IntegerField()),
                ('total_size', models.DecimalField(decimal_places=8, help_text='Total pool size in MATIC', max_digits=20)),
                ('remaining_size', models.DecimalField(decimal_places=8, help_text='Remaining capacity in MATIC', max_digits=20)),
                ('contract_pool_id', models.IntegerField(help_text='Pool ID on the smart contract', unique=True)),
                ('is_settled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('wallet_address', models.CharField(blank=True, default='', max_length=42)),
                ('total_invested', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('active_investments', models.IntegerField(default=0)),
                ('total_returns', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='Supabase user UID', max_length=100)),
                ('wallet_address', models.CharField(max_length=42)),
                ('amount', models.DecimalField(decimal_places=8, help_text='Amount in MATIC', max_digits=20)),
                ('tx_hash', models.CharField(help_text='Transaction hash', max_length=66, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='core.pool')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('tx_type', models.CharField(choices=[('invest', 'Invest'), ('withdraw', 'Withdraw')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pool')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
