# Generated by Django 5.2.13 on 2026-07-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='Supabase user UID', max_length=100)),
                ('transaction_hash', models.CharField(db_index=True, max_length=66)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('email_type', models.CharField(choices=[('investment_success', 'Investment Success'), ('investment_failed', 'Investment Failed'), ('settlement', 'Settlement')], max_length=30)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=10)),
                ('provider', models.CharField(default='brevo', max_length=30)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
