# Generated by Django 5.2.13 on 2026-07-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emaillog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='error_message',
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(help_text='e.g. investment_confirmation', max_length=50),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='provider',
            field=models.CharField(default='brevo', max_length=50),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='transaction_hash',
            field=models.CharField(max_length=66),
        ),
    ]
