# Generated by Django 5.2.13 on 2026-07-22 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_emaillog_error_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_uid', models.CharField(help_text='auth.users.id from Supabase', max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('role', models.CharField(choices=[('INVESTOR', 'Investor'), ('EXPORTER', 'Exporter'), ('LAW_FIRM', 'Law Firm'), ('ADMIN', 'Admin')], default='INVESTOR', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LawFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=200)),
                ('business_email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='law_firm', to='core.appuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.appuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outstanding_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('recovery_stage', models.CharField(choices=[('DEFAULT', 'Default'), ('LEGAL_NOTICE_SENT', 'Legal Notice Sent'), ('NEGOTIATION', 'Negotiation'), ('SETTLEMENT', 'Settlement'), ('RECOVERED', 'Recovered'), ('CLOSED', 'Closed')], default='DEFAULT', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_cases_as_exporter', to='core.appuser')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_cases_as_investor', to='core.appuser')),
                ('law_firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_cases', to='core.lawfirm')),
                ('pool', models.ForeignKey(help_text='The invoice pool this recovery case is for', on_delete=django.db.models.deletion.CASCADE, related_name='recovery_cases', to='core.pool')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LEGAL_NOTICE_SENT', 'Legal Notice Sent'), ('NEGOTIATION_STARTED', 'Negotiation Started'), ('SETTLEMENT_RECORDED', 'Settlement Recorded'), ('PARTIAL_RECOVERY', 'Partial Recovery'), ('FULL_RECOVERY', 'Full Recovery'), ('CASE_CLOSED', 'Case Closed'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('NOTE_ADDED', 'Note Added')], max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('document_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to='core.appuser')),
                ('recovery_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.recoverycase')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
