# Generated by Django 5.2.13 on 2026-07-22 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appuser_lawfirm_notification_recoverycase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When this investment was completed/returned', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='expected_profit',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Server-computed expected profit', max_digits=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='returns_due_at',
            field=models.DateTimeField(blank=True, help_text='When returns are expected — countdown target', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='roi',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ROI percentage for the pool duration', max_digits=6),
        ),
        migrations.AddField(
            model_name='investment',
            name='transaction_fee',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Platform fee taken on this investment', max_digits=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='completed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='current_value',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Total current value of all investments', max_digits=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pending_returns',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Expected returns from active investments', max_digits=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_profit',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Total realised profit from completed investments', max_digits=20),
        ),
        migrations.AddField(
            model_name='recoverycase',
            name='investment',
            field=models.ForeignKey(blank=True, help_text='The specific investment that defaulted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_cases', to='core.investment'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
