# Generated by Django on 2026-07-28

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def migrate_legacy_invoice_rows(apps, schema_editor):
    Invoice = apps.get_model('core', 'Invoice')
    for invoice in Invoice.objects.all():
        created_date = timezone.localdate(invoice.created_at) if invoice.created_at else timezone.localdate()
        old_status = getattr(invoice, 'status', '') or ''
        status_map = {
            'UPLOADED': 'Draft',
            'VERIFIED': 'Verified',
            'POOL_CREATED': 'Funding',
        }

        invoice.invoice_number = invoice.invoice_number or f'INV-{invoice.pk}'
        invoice.buyer_company = invoice.buyer_company or invoice.buyer_name
        invoice.amount = invoice.amount if invoice.amount is not None else invoice.invoice_amount
        invoice.issue_date = invoice.issue_date or created_date
        invoice.country = invoice.country or invoice.buyer_country or 'United States'
        invoice.status = status_map.get(old_status, old_status or 'Verified')
        invoice.save(update_fields=[
            'invoice_number',
            'buyer_company',
            'amount',
            'issue_date',
            'country',
            'status',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_company',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(
                choices=[
                    ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'),
                    ('INR', 'Indian Rupee'), ('AED', 'UAE Dirham'),
                    ('SGD', 'Singapore Dollar'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'),
                ],
                default='USD',
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='funded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='blockchain_hash',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(migrate_legacy_invoice_rows, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='invoice',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='buyer_email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='buyer_country',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='verified_at',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='buyer_company',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='country',
            field=models.CharField(default='United States', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='exporter',
            field=models.ForeignKey(
                blank=True,
                help_text='AppUser with EXPORTER role who uploaded this invoice',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='invoices',
                to='core.appuser',
            ),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(
                choices=[
                    ('Draft', 'Draft'), ('Verified', 'Verified'), ('Funding', 'Funding'),
                    ('Funded', 'Funded'), ('Active', 'Active'), ('Completed', 'Completed'),
                ],
                default='Verified',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='InvoicePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_size', models.DecimalField(decimal_places=2, max_digits=20)),
                ('expected_roi', models.DecimalField(decimal_places=2, help_text='Expected ROI percentage, e.g. 12.50', max_digits=6)),
                ('funding_deadline', models.DateField(help_text='Must be before invoice due date')),
                ('min_investment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('max_investment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount_funded', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('is_visible_to_investors', models.BooleanField(default=True, help_text='When True, investors can see and invest in this pool')),
                ('status', models.CharField(choices=[('open', 'Open'), ('fully_funded', 'Fully Funded'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pool', to='core.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('uploaded', 'Uploaded'), ('verified', 'Verified'), ('pool_created', 'Pool Created'), ('funded', 'Funded'), ('matured', 'Matured'), ('status_changed', 'Status Changed')], max_length=30)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.invoice')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='core.invoicepool')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='core_invoic_status_3d8780_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='core_invoic_due_dat_a17de6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='core_invoic_invoice_aef6bc_idx'),
        ),
    ]
