# Generated by Django 6.0.7 on 2026-07-22 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_investment_completed_at_investment_expected_profit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_company', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('INR', 'Indian Rupee'), ('AED', 'UAE Dirham'), ('SGD', 'Singapore Dollar'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan')], default='USD', max_length=5)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('po_number', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('pdf_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Verified', 'Verified'), ('Funding', 'Funding'), ('Funded', 'Funded'), ('Active', 'Active'), ('Completed', 'Completed')], default='Verified', max_length=20)),
                ('funded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('blockchain_hash', models.CharField(blank=True, default='', max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exporter', models.ForeignKey(blank=True, help_text='AppUser with EXPORTER role who uploaded this invoice', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.appuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_size', models.DecimalField(decimal_places=2, max_digits=20)),
                ('expected_roi', models.DecimalField(decimal_places=2, help_text='Expected ROI percentage, e.g. 12.50', max_digits=6)),
                ('funding_deadline', models.DateField(help_text='Must be before invoice due date')),
                ('min_investment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('max_investment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount_funded', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('is_visible_to_investors', models.BooleanField(default=True, help_text='When True, investors can see and invest in this pool')),
                ('status', models.CharField(choices=[('open', 'Open'), ('fully_funded', 'Fully Funded'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pool', to='core.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('uploaded', 'Uploaded'), ('verified', 'Verified'), ('pool_created', 'Pool Created'), ('funded', 'Funded'), ('matured', 'Matured'), ('status_changed', 'Status Changed')], max_length=30)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.invoice')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='core.invoicepool')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='core_invoic_status_3d8780_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='core_invoic_due_dat_a17de6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='core_invoic_invoice_aef6bc_idx'),
        ),
    ]
