# Generated by Django 5.2.13 on 2026-07-23 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_investment_completed_at_investment_expected_profit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('buyer_country', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VERIFIED', 'Verified'), ('POOL_CREATED', 'Pool Created')], default='UPLOADED', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.appuser')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.pool')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
