# Generated by Django 6.0.7 on 2026-07-26 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invoice_invoicepool_uploadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepool',
            name='investment_pool',
            field=models.OneToOneField(blank=True, help_text='Unified investor-facing pool row linked to this invoice pool', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_pool_metadata', to='core.pool'),
        ),
        migrations.AddField(
            model_name='pool',
            name='buyer_company',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='pool',
            name='buyer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pool',
            name='currency',
            field=models.CharField(blank=True, default='MATIC', max_length=5),
        ),
        migrations.AddField(
            model_name='pool',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='exporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_pools', to='core.appuser'),
        ),
        migrations.AddField(
            model_name='pool',
            name='funding_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_pool', to='core.invoice'),
        ),
        migrations.AddField(
            model_name='pool',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pool',
            name='max_investment',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='pool',
            name='min_investment',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='pool',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
