# Generated by Django 5.2.13 on 2026-09-07 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_invoicepool_investment_pool_pool_buyer_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='can_export',
            field=models.BooleanField(default=False, help_text='When True, user has exporter capabilities (via KYC upgrade)'),
        ),
        migrations.CreateModel(
            name='KYCApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('auto_approve_at', models.DateTimeField(blank=True, help_text='Demo mode: auto-approve at this UTC datetime', null=True)),
                ('user', models.OneToOneField(help_text='One KYC application per user', on_delete=django.db.models.deletion.CASCADE, related_name='kyc_application', to='core.appuser')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
