# Generated by Django 5.2.13 on 2026-09-07 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_kyc_and_can_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverycase',
            name='bid_deadline',
            field=models.DateTimeField(blank=True, help_text='Auction deadline — highest bidder wins when this passes', null=True),
        ),
        migrations.AlterField(
            model_name='invoicepool',
            name='funding_deadline',
            field=models.DateTimeField(help_text='Deadline for pool to be fully funded (minute-granularity for demo)'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='funding_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RecoveryBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=8, help_text='Amount in MATIC the law firm is willing to pay the pool', max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='core.recoverycase')),
                ('law_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='core.lawfirm')),
            ],
            options={
                'ordering': ['-bid_amount', 'created_at'],
            },
        ),
    ]
