# Generated by Django 5.2.13 on 2026-09-08 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_demo_mode_and_recovery_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Verified', 'Verified'), ('Funding', 'Funding'), ('Funded', 'Funded'), ('Active', 'Active'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='Verified', max_length=20),
        ),
        migrations.AlterField(
            model_name='recoverycase',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_cases_as_investor', to='core.appuser'),
        ),
    ]
